# Generated by Django 4.1.3 on 2022-12-12 23:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fallout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charfallout',
            name='armasMeleeSkill',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Armas Melee'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='armasMeleeTag',
            field=models.BooleanField(default=False, verbose_name='Armas Melee Tag'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='nombreJugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
